on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20.x
            - name: Install Yarn
              run: npm install -g yarn
            - name: Build Client
              run: |
                  cd packages/client 
                  yarn 
                  npm run build
            - name: Build Extension
              run: |
                  cd packages/extension
                  yarn
                  yarn compile
            - name: Publish
              run: |
                  cd packages/extension
                  yarn deploy
              env:
                  VSCE_PAT: ${{ secrets.VSCE_PAT }}
