on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20.x
            - run: |
                  npm install -g yarn
                  cd packages/client 
                  yarn 
                  npm run build
                  cd packages/extension
                  yarn
                  yarn compile
            - name: Publish
              run: yarn deploy
              env:
                  VSCE_PAT: ${{ secrets.VSCE_PAT }}
